# Generated by Django 5.0.6 on 2024-06-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('company', 'Company'), ('admin', 'Admin')], default='customer', max_length=20),
            preserve_default=False,
        ),
    ]
