# Generated by Django 5.0.6 on 2024-06-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('company', 'Company'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
