# Generated by Django 5.0.6 on 2024-07-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
